### ISSUE TITLE
What are the differences between bluedata/cdh5142cm and the official cdh docker images?

### ISSUE THREAD

**Issue by yingfeng** [bluek8s/kubedirector#145]
The example deploy catalog config file adopts docker.io/bluedata/cdh5142cm:3.0 as the cdh docker image to be deployed using kubedirector, so does there exist any difference between this one and the official cdh docker images? Could I replace it with the official one in the deploy catalog configuration?

**Comment by joel-bluedata** [comment]
There will be differences. In general this image will have as much stuff as possible "preinstalled" in a state that is ready for final reconfiguration (with things like worker host identities and selected services) at deploy time. I'll get the guy who worked on this image to come over to this thread and comment more.

**Comment by kmathur2** [comment]
@joel-bluedata yes Joel you are correct about most of the "preinstalled" . Just looking at cloudera's website about their docker image it seems that its just a single container that you can bring up using docker run for trying and learning stuff, however with the example of cdh with kubedirector you can bring up entire cdh "cluster" with parcels distributed and activated  across worker and master nodes and services correctly configured. After we take care few pending features these images will support HDFS , YARN HA and seamless migration of nodes in case of hose failure

**Comment by yingfeng** [comment]
Hi, @joel-bluedata @kmathur2 
Could the dockerfile of bluedata/cdh5142cm be provided? Thank you~

**Comment by joel-bluedata** [comment]
Sure! We should figure out a good way to advertise/manage more of our example catalog source materials.

FYI: to leverage some of the "day job" work from EPIC contributors who are also KD contributors, this (and some other) catalog images are based on a BlueData EPIC base catalog image. In this case it is based on bluedata/centos7. I'll attach the Dockerfile for that as Dockerfile.bluedata-centos7-base.txt here.

Then the actual Dockerfile for the CDH catalog entry is attached here as Dockerfile.kd-cdh5142.txt. (Again this is built on some of the CDH image work done for the EPIC catalog.)

Because of their "origin story", I'm sure that some of the bits in these Dockerfiles are not necessary for supporting KD functionality, or at least not yet. So they could be confusing. If you have specific questions about the Dockerfiles then either @kmathur2 or @swamibluedata could address them. However we should keep this particular GitHub issue conversation at a high level, maybe just tackling some discussion of how to use an unmodified CDH image or how to best publish the example catalog materials. For other more low-level detail discussion the [BlueK8s Slack workspace](https://join.slack.com/t/bluek8s/shared_invite/enQtNTQzNDQzNjQwMDMyLTdjYjE0ZTg0OGJhZWUxMzhkZTZjNDg5ODIyNzZmNzZiYTk4ZjQxNDFjYzk4OWM0MjFlNmVkNWNlNmFjNzkzNjQ) might be better.

[Dockerfile.bluedata-centos7-base.txt](https://github.com/bluek8s/kubedirector/files/2886372/Dockerfile.bluedata-centos7-base.txt)
[Dockerfile.kd-cdh5142.txt](https://github.com/bluek8s/kubedirector/files/2886373/Dockerfile.kd-cdh5142.txt)

**Comment by yingfeng** [comment]
Thank you!
