### ISSUE TITLE
harden object-update behavior

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#178]
On the new operator SDK branch, we can't do a PATCH through the client because there's not a stable version of controller-runtime that supports PATCH yet. So we have to do read-modify write in cases where we were previously doing a PATCH. But that is racy and could fail with a resourceVersion conflict if some other client modifies the object around the same time.

We need to gracefully handle failure and retry. The most custom-controller-ish way to handle this I think is to bail out of the reconciliation handler so that it can try again at the next polling interval. We would need to take a close survey of the code locations that do this kind of update to see how to best fail our way out of the handler from that point, and whether that naturally leaves us in a consistent state that can be picked up again by the next reconciliation pass.

The main exception to this would be the update of the KDC status, which is required to succeed before exiting the handler (because that's where we keep important persistent state that drives reconciliation). In that case if the update fails we have to keep retrying, with no exit conditions other than success or object-not-found.

**Comment by don-milos** [comment]
The code in controller/kubedirector_cluster.go/Reconcile() does just what you describe. On error the reconcile.result contains the error so the request is requeued to be tried again.

Also, I believe the controller/kubedirectorcluster_controller/cluster.go/syncCluster() function already retries (forever) the UpdateStatus request until success or object-not-found before it will exit.

**Comment by joel-bluedata** [comment]
Yeah I think the status update func in syncCluster is OK, I just wanted to make a note that we should not break its retry-forever behavior as we mess with PATCH implementations.

As for the other spots, I'm talking about the lower-level code that does the object update such as in executor.UpdateStatus or RemoveFinalizer etc. (basically spots where errors.IsConflict is currently being checked). We have code that retries once and then returns an error if that single retry fails.

My original proposal was not for a single retry, but rather to retry until success. My revised proposal however was that we should have the courage of our convictions (about our operator/reconciliation model) and not even retry once. If there's an error, we should exit the handler cleanly and rely on the next handler go-around to try again. Need to examine these spots and make sure that is indeed safe to do.

**Comment by don-milos** [comment]
There is a pre-existing comment at lines 52-53 in syncCluster() to note that we should try forever:

        // Write back the status. Don't exit this reconciler until we
        // succeed (will block other reconcilers for this resource).

Even though executor/cluster.go/UpdateStatus() only tries twice to update the status we've already verified that the loop in syncCluster() will try to update the status forever, by calling updateStatus(), until it succeeds or the resource is deleted.

There were only 4 other places where the old code used sdk.Patch():

1. executor/statefulset.go/UpdateStatefulSetReplicas()
2. executor/cluster.go/RemoveFinalizer()
3. executor/cluster.go/EnsureFinalizer()
4. executor/service.go/UpdatePodService()

In the old code, none of these operations tried forever. They tried once and returned an error. In the new code, when an error is generated, the reconciler will requeue the request and reconcile the resource again on the next pass.

I don’t think there’s anything left that we need to do for this issue?

**Comment by joel-bluedata** [comment]
We might need to have an in-person talk just to streamline the issue here, I think we may have thrown up too much dust around it. But my opinion pretty much boils down to:

- Trying twice is not really useful; it just adds code complexity. Either failure is OK (in which case we can just try once) or its not (in which case we should loop until success).
- I think it's likely that failure is OK, we just need to audit what those code spots will do in that case. I can take a whack at that if you like.

Note that in the old code with the PATCH we did not expect failure, because we were not providing a resourceVersion in our change. We still checked for errors because of course, but in the old code error was an exceptional condition that didn't necessarily need to be recoverable, while in the new code an error can be the result of a perfectly legal and not-too-unlikely race condition.

**Comment by joel-bluedata** [comment]
OK here's the "audit":

### if UpdateStatefulSetReplicas fails
* checkMemberCount returns false
* handleCreatePendingMembers or handleDeletingMembers will return early
* those members will not get modified during syncMembers
* next handler pass (probably just on poll interval) will try again

### if RemoveFinalizer fails
* handleFinalizers will still remove the status gen and cluster app reference; returns error
* syncCluster returns an error
* Reconcile returns an error, so next handler should immediately queue up
* next handler: syncCluster puts the app reference back
* handleFinalizers tries RemoveFinalizer again
* handleFinalizers will also do DeleteStatusGen and RemoveClusterAppReference again which should be fine

### if EnsureFinalizer fails
* handleFinalizers returns error
* syncCluster returns an error
* Reconcile returns an error, so next handler should immediately queue up
* next handler: handleFinalizers tries EnsureFinalizer again

### if UpdatePodService fails
* handleMemberServiceConfig returns error
* no one cares though
* next handler pass (on poll) will try again if reconcile is still needed


So I think that's all fine.

The upshot for this issue really just seems to be that we should not bother with the second PUT attempt inside the same handler when a resourceVersion conflict happens. If the first attempt fails, we should return the error and get on with things.

One kind of odd behavior is that we remove and re-add the cluster app reference in the case where RemoveFinalizer fails. This is a consequence of the fact that syncCluster does EnsureClusterAppReference as the very first thing up top. That's not terrible, although I think we had discussed moving EnsureClusterAppReference down so that it only occured AFTER handleFinalizers. I don't exactly remember why we left it up top... maybe just not motivated enough to move it?

**Comment by don-milos** [comment]
We should probably talk offline about this issue. I'm not really .

> That's not terrible, although I think we had discussed moving EnsureClusterAppReference down so that it only occured AFTER handleFinalizers. I don't exactly remember why we left it up top... maybe just not motivated enough to move it?

We talked about switching the order of handling finalizers and statusgen's, not app references. Here's where we talked about finalizers and statusgen's: https://github.com/bluek8s/kubedirector/pull/171#issuecomment-505536810

> So in the KDC reconciler, we want to make sure we don't do any processing for a CR that has a deletion timestamp, beyond (if necessary) removing its finalizer and removing its status gen from the cache. It looks like handleFinalizers already takes care of that. However, the current ordering of the calls to handleNewCluster (used to be handleStatusGen) and handleFinalizers is unfortunate in that handleNewCluster would re-add the status gen back into the cache. I believe the simplest answer to that problem is to switch the order that those functions are called -- always do handleFinalizers first. I think the reason that the invocations were in their current order was to properly ignore stale poll handlers (which is no longer an issue).

I don't think there is any harm in leaving the EnsureClusterAppReference call where it currently is. After all it's just updating an in-memory map.

Correct me if I'm wrong but if we move the EnsureClusterAppReference down then arent't we opening up the window further where the app could be deleted while the KD Cluster is being created? Especially if we're going to let errors be dealt with on the next reconciler iteration. There's 30 seconds between each reconciler iteration.

Will the cluster creation fail somewhere futher down in the code if the app was deleted in between?

Regarding the second PUT attempts, I would prefer to leave them in place. We could discuss this offline but here's my reasoning:

- We agreed early on that we would attempt a PUT, if that failed because the current object was out of date the we would fetch the current object, modify the appropriate properties, and attempt to PUT that, more up to date, version of the object. I've put in alot of testing with this implementation over the last month.

- That sequence is the recommended way to migrate PATCH operations to the new operator-sdk in many Kubernetes issues on the web and in the Kubernetes documentation.

- To understand the impact of removing the second PUT I added logging to let us know when the second PUT was necessary. After I added the logging I deployed a KD Cluster and got the following log messages.

{
"level":"error"
"ts":1565384034.2671394
"logger":"controller_kubedirectorcluster"
"msg":"failed to add finalizer - retrying"
"Request.Namespace":"default"
"Request.Name":"centos7-persistent"
"error":"admission webhook \"validate-cr.kubedirector.bluedata.io\" denied the request: 
KubeDirector-related status properties are read-only"
"stacktrace":"github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr.(*zapLogger).Error
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/bluek8s/kubedirector/pkg/shared.LogError
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/shared/logging.go:78
github.com/bluek8s/kubedirector/pkg/executor.EnsureFinalizer
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/executor/cluster.go:183
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).handleFinalizers
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:249
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:92
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).Reconcile
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go:102
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.Until
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}

{
"level":"error"
"ts":1565384034.2906327
"logger":"controller_kubedirectorcluster"
"msg":"failed to update status - retrying"
"Request.Namespace":"default"
"Request.Name":"centos7-persistent"
"error":"Operation cannot be fulfilled on kubedirectorclusters.kubedirector.bluedata.io \"centos7-persistent\": the object has been modified; please apply your changes to the latest version and try again"
"stacktrace":"github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr.(*zapLogger).Error
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/bluek8s/kubedirector/pkg/shared.LogError
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/shared/logging.go:78
github.com/bluek8s/kubedirector/pkg/executor.UpdateStatus
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/executor/cluster.go:55
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:56
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:106
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).Reconcile
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go:102
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.Until
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}

{
"level":"error"
"ts":1565384034.3802066
"logger":"controller_kubedirectorcluster"
"msg":"failed to update statefulset - retrying"
"Request.Namespace":"default"
"Request.Name":"centos7-persistent"
"error":"Operation cannot be fulfilled on statefulsets.apps \"kd-gq4mx\": the object has been modified; please apply your changes to the latest version and try again"
"stacktrace":"github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr.(*zapLogger).Error
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/bluek8s/kubedirector/pkg/shared.LogError
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/shared/logging.go:78
github.com/bluek8s/kubedirector/pkg/executor.UpdateStatefulSetReplicas
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/executor/statefulset.go:79
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.checkMemberCount
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/members.go:487
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.handleCreatePendingMembers
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/members.go:170
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.syncMembers
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/members.go:72
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).syncCluster
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/cluster.go:171
github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster.(*ReconcileKubeDirectorCluster).Reconcile
/alt/root/go/src/github.com/bluek8s/kubedirector/pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go:102
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait.Until
/alt/root/go/src/github.com/bluek8s/kubedirector/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}

- The operations eventually succeeded, after the next reconciler pass, but if we don't retry the PUTs with a more up to date version of the objects then we will always get these errors in the logs. I think that looks sloppy.

Since we're only updating a portion of the object, just like sdk.Patch() did, then I'm don't think I see an issue. The code is not really that much more complex since the retry is isolated in a few small functions. Once Patch() is available again we can re-simplify these functions.

Let's talk offline when you get a chance.

**Comment by joel-bluedata** [comment]
Can you point me at at example of two of what you ran across w.r.t. "the recommended way to migrate PATCH operations"?

**Comment by don-milos** [comment]
I was only able to find this one.

https://github.com/operator-framework/operator-sdk/issues/1077

"But for now since Patch() is just an optimization you should be able to replace it with a Get() followed by an Update(). Or just create the raw rest client to use the Patch() function directly."

**Comment by don-milos** [comment]
I know I had seen other examples when I was researching this issue but I'm not able to find them now but event the example of how to use Update includes the Get -> modify obj -> Update sequence. We had decided to attempt the update with the original object for efficiency.

The Update example I mentioned above is on this page: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md .

**Comment by joel-bluedata** [comment]
Got it. OK... I would recommend the following then:

* For the status update, since we are updating the whole subresource, we shouldn't need to retry inside of the executor.UpdateStatus function. (And if that shared.Client().Status().Update() does fail for some reason, the UpdateStatus caller in syncCluster is going to loop anyway.) So let's remove the retry from the executor.UpdateStatus code.

* File a JIRA to remind us to move the other four spots back to using PATCH in the future when the controller-runtime supports that.

* Make a comment at those four spots in the code, referencing the JIRA.

**Comment by don-milos** [comment]
I made the requested changes and created the following pull request: https://github.com/bluek8s/kubedirector/pull/195 .
