### ISSUE TITLE
allow role requests for GPUs

### ISSUE THREAD

**Issue by joel-bluedata** [bluek8s/kubedirector#23]
(analogous to requesting CPU, memory)

**Comment by swamibluedata** [comment]
https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

App CR spec will have optional "resources" under "roles"

                  resources:
                    gpu:
                      required: [min_count]
                      properties:
                        min_count:
                          type: integer
                        limit_vendors:
                          type: array
                          items:
                            type: string


limit_vendors is optional and can limit the vendors that can be used by cto filuster Cars

Cluster CRD  will have optional field 
<vendor>.com/gpu tag in the "limits" section. 

We will validate for limit_vendors and min_count using app spec


Is there anyway to specify this in the cluster CR, since <vendor> can be dynamic?

**Comment by swamibluedata** [comment]
Will this work in cluster cr 

                          "^.*\.com/gpu$":
                            type: integer

**Comment by swamibluedata** [comment]
Well v1.10.1 supports only nvidia gpu tag

	ResourceNvidiaGPU ResourceName = "alpha.kubernetes.io/nvidia-gpu"

So i am going to change this to just use this.

**Comment by swamibluedata** [comment]
Ended up just changing the app crds to support nvidia.com/gpu and amd.com/gpu
