### ISSUE TITLE
Feature Request: provide instructions for running on minikube

### ISSUE THREAD

**Issue by snowch** [bluek8s/kubedirector#275]
I would like to learn about kubedirector on my laptop when I am travelling with no/poor Internet connection.  It would be really good to have instructions for setting up KD on minikube.

**Comment by joel-bluedata** [comment]
I suspect that you filed this issue because you tried and it didn't work? Any specific symptom?

Historically we did have issues with OpenShift. Those have been pared down to issue #3 at this point. Until we try again on a recent-version OpenShift setup, we can't really be sure whether issue #3 still applies, or alternately whether the allegedly no-longer-an-issue issues really are such. Trying minikube (when we have the chance) would be one way to poke at this.

**Comment by joel-bluedata** [comment]
I did a quick standup of minikube using homebrew, then "make deploy" of KD, then "kubectl create" of a simple CentOS kdcluster. Seems to work! I'm sure there's more to figure out about recommended setup for services (NodePort vs. LoadBalancer), and persistent storage, and giving minikube enough CPU/mem resources, but nothing fundamentally prevented the creation of the kdcluster.

**Comment by joel-bluedata** [comment]
Going to close this in the absence of any specific issues reported.
