### ISSUE TITLE
Support setting up serviceAccounts for role

### ISSUE THREAD

**Issue by swamibluedata** [bluek8s/kubedirector#475]
To support applications that will have to interact with api server, it is essential to support serviceaccount injection to all member of a role. User would have created the service account prior to this. (For ECP created tenant, we have the serviceAccount automatically created).

Can we support this through cluster cr definition?

**Comment by kmathur2** [comment]
We have connections that currently takes (configmap, secret, cluster) maybe we can add service account to that.

**Comment by joel-bluedata** [comment]
There's an interesting twist/variant for this that we've been discussing elsewhere. If the kdapp is an operator (or similar thing), it may need very wide privileges for its service account... you may in fact not want to have a service account with those privs existing within the same namespace as the kdcluster. I.e. your cluster admin may have decided it's OK for you (working within this namespace) to deploy this specific kdapp that has wide privileges, but not for you to be able to create/deploy other kdapps or pods etc. that have the same set of privs.

We need some sort of feature where a cluster admin can "bless" certain roles for certain kdapp distro IDs, to give them the ability to do k8s API requests with certain privileges from inside their containers. Probably need a kdapp checksum there as well to make sure it's the one we think it is.

This "blessing" could be done by doing things in the KD namespace, for example editing the KD config to list the role/distroID/checksums in question.

The privileges (Role resource content) probably need to be described by the kdapp, and then KD would do what to get those privs usable from within the container? Since we can't assume any particular kind of external authn/authz support, it seems like service accounts are what we have to work with. I need to refresh my understanding of the kinds of shenanigans we could do here, but for example maybe KD would: create the relevant role in the kdcluster's namespace, create a service account in the *KD* namespace, bind that SA to that role. Then have KD explicitly copy the SA token into appropriate containers when needed.
